### PR TITLE
Update default context of analytics events.

### LINKED ISSUE #319: Add window size to tracking context
on iPad we have different options to display the app (split mode) which are independent of the screen size.
This should be consistent between iOS and Android.

### PR DESCRIPTION
**Pull request by mathebox**
Fixes #319

### Proposed Changes:
- Revise naming
- Add window size
- Add client id.

### CODE REVIEW

**Comment by mathebox** [comment]
@jprberlin yes we definitely have to check this!

**Comment by jprberlin** [comment]
its ok: https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor

**Comment by bjrne** [comment]
But my question remains unanswered?

**Comment by mathebox** [comment]
You could own the same iPhone models twice. Somehow you have to distingush between those devices.

**Comment by bjrne** [comment]
Okay, I understand the scenario, but do we really care about that it it is the same account and two mobile devices? Also given that the id can always change at any moment?

**Comment by bjrne** [comment]
Okay forget that, I thought this property wouldn't exist anymore and we only had the advertisement identifier left.

**Comment by mathebox** [comment]
:) the identifier for vendors remains the same for one app installation

**Pull request merged**
