### PR TITLE
Add user, user-profile, login apiv2

### PR DESCRIPTION
**Pull request by bjrne**
When this is merged, we are using APIv2 for all communication with the server

### CODE REVIEW

**Comment by jprberlin** [comment]
Can we remove the old api usage from code/ like in the routes file ?

**Comment by bjrne** [comment]
I'd suggest a separate PR for that including all cleanup work we can do then like removing unused pods for api parsing etc.

**Comment by rhlff** [comment]
It seems to break the tvOS builds.

**Comment by jprberlin** [comment]
Wasn’t tvOS broken before? Can nik can have a look at that?

**Pull request merged**
